const { fs } = require('./modules')

let dataValues = {}

dataValues.statuses = JSON.parse(fs.readFileSync('./assets/json/statuses.json'))
dataValues.json = {
    wordJSON: JSON.parse(fs.readFileSync('./assets/json/words.json')),
    fakeWordJSON: JSON.parse(fs.readFileSync('./assets/json/fakeWords.json')),
    continentJSON: JSON.parse(fs.readFileSync('./assets/json/continents.json')),
    countryJSON: JSON.parse(fs.readFileSync('./assets/json/countries.json')),
    languageJSON: JSON.parse(fs.readFileSync('./assets/json/languages.json')),
    cityJSON: JSON.parse(fs.readFileSync('./assets/json/cities.json')),
    restaurantJSON: JSON.parse(fs.readFileSync('./assets/json/foods.json')),
    sentenceJSON: JSON.parse(fs.readFileSync('./assets/json/sentences.json')),
    nounJSON: JSON.parse(fs.readFileSync('./assets/json/nouns.json')),
    verbJSON: JSON.parse(fs.readFileSync('./assets/json/verbs.json')),
    adjJSON: JSON.parse(fs.readFileSync('./assets/json/adjectives.json')),
    imageJSON: JSON.parse(fs.readFileSync('./assets/json/images.json')),
    nameJSON: JSON.parse(fs.readFileSync('./assets/json/names.json')),
    emojiJSON: []
}
dataValues.arrays = {
    arabDictionary: [
        '4chan', 'the poopening', 'negro', 'feet', 'GIANT COCK', 'orgy',
        'e621', 'cum', 'r34', 'mug', 'Talking Tom', 'Talking Ben', 'Talking Angela',
        'IShowSpeed', 'deepwoken', 'pilgrammed', 'lean', '🤓', 'punapea6', 'dream', 'soup land',
        'phexonia studios', 'idfsgs', 'penis', 'sex', 'hentai', 'area', 'World', 'throat',
        'Mongolian', 'finnish', 'Malagasy', 'Iraqi', 'polish', 'ethiopian', 'canadian',
        'ukrainian', 'iranian', 'irish', 'swedish', 'danish', 'french', 'chips', 'spanish',
        'racist', 'superbrohouse', 'deinx', 'bubbley', 'deinbag', 'another', 'crypyth',
        'tordenask', 'lead', 'wovxzers', 'dootings', 'bartekoklol', 'tuca', 'ballfish', 'kleio',
        'crazy', 'cinna', 'btn', 'tree', 'gritzy', 'ruki', 'henry', 'empsy', 'maks', 'henhen',
        'phex', 'icre8', 'bilon', 'fnepp', 'zekkriel', 'tranzst', 'mance', 'luigistar', 'makos',
        'spellbunny', 'scriptedsand', 'puppet', 'josh', 'spooky', 'catfishhotdog', 'robuk',
        'pl0x7', 'lemoardo', 'dundeed', 'notsam', 'luigiluis', 'trongal', 'mysterymeatwad',
        'carlito', 'azureblob', 'simpremove', 'gobby', 'sayori', 'concern', 'betteruser', 'tix',
        'charleh', 'jlol', 'Featured', 'Vesteria', 'Rogue Lineage', 'madness', 'tricky', 'zardy',
        'madness combat', 'splatoon', 'babis', 'wiki', 'fandom', 'milk', 'carrot', 'vinegar',
        'mushroom', 'stew', 'shroom', 'peashooter', 'eyed', 'pea', 'frank', 'carl', 'oil',
        'sunflower', 'chomper', 'piranha', 'fishes', 'fishe', 'fish', 'salami', 'lid', '≥w≤',
        'furry', 'nya', 'uwu', 'owo', '^w^', 'freedom', 'dick', 'flip', 'bottle', 'pork',
        'demotion', 'promotion', 'Error', 'Scream', 'spoon', 'knife', 'all over', 'african',
        'land', '😂', 'yup', 'pee', 'piss', 'stranger language', 'edition', 'version', 'turtle',
        'language', 'stranger', 'persian', 'people', 'Freddy', 'FNAF', 'giraffe', 'hippopotamus',
        'program', 'coding', 'ocean', 'treasure', 'egg', 'tool', 'lad', 'lad village', 'GPU',
        'CPU', 'lag', 'imposter', 'Among Us', 'sus', 'homework', 'markov', 'moment', 'nervous',
        'shy', 'CHICKEN', 'sosig', 'brogle', 'Dad', 'Grand', 'Windows 95', 'Windows XP',
        'big fat', 'blender', 'group', 'Phexonia', 'venezuelan', 'tf2', 'Bastard', 'obby',
        'david', 'WARIO', 'sandals', 'livestream', 'youtube', 'minimum', 'pickle', 'NSFW',
        'hot', 'RALEIGH', 'PEED FAMILY', 'gif', 'nostalgia critic', 'Britain', 'America',
        'United Kingdom', 'soup', 'United States of America', 'WOMEN', 'wife', 'cat',
        'marselo', 'tech support', 'indian', 'australian', 'japanese', 'Plants vs Zombies',
        'Joe Biden', 'chinese', 'Chinese Republic', 'french fries', 'german', 'SWITZERLAND',
        'denmark', 'Donald Trump', 'portuguese', 'nigerian', 'russian', 'beach', 'alpha',
        'beta', 'theaters', 'Movie', 'Trailer', 'Lego', 'chalk', 'Documentation', 'mcdrive',
        'Boner', 'Big', 'Giant', 'Small', 'Awesome', 'STOLEN', 'no', 'yes', 'car', 'Rigby',
        'Mordecai', 'BENSON', 'park', 'blaster', 'gaster', 'Undertale', 'phil', 'Anvil',
        'halloween', 'pumpkin', 'shut up', 'platinum', 'cheats', 'farms', 'GOLD', 'cake day',
        'pizza slice', 'lasagna', 'quesadilla', 'enchilada', 'Miner\'s Haven', 'berezaa',
        'LEGENDARY', 'Bee Swarm Simulator', 'beta tester', 'member', 'creator', 'family',
        'Empire', 'Warfare', 'upvotes', 'downvotes', 'redditor', 'reddit', 'reddit arguments',
        'twitter', 'twitter arguments', 'amongla', 'virus', 'viruses', 'INSTALL NOW',
        'FL Studio VST', 'Torrent', 'Github', 'the ESSENCE', 'soup satan', 'soup god',
        'quesley', 'empsy', 'illegal', 'legal', 'regal', 'deflorestation', 'DONKEY KONG',
        'piss shit come', 'gay chains', 'Tss crazed', 'ralsei', '👶', '✅', 'PIG', 'cucumber',
        'mark\'s pizzeria', 'dominus pizza', 'pizza hut', 'wendy\'s', 'hat', 'tool',
        'burger king', 'mcdonalds', 'nugget', 'fat', 'WTF', 'ROFL', 'XD', 'LMAO', 'LOL', 'Lad',
        'Piid', 'LOUD', 'griefed', 'Fitmc', '2b2t', 'POPBOB', 'mommy', 'Survival', 'Jeff',
        'Slender', 'Piggy', '🐖', 'artistic', 'Burrito', 'fart channel', '💓', 'Banjo',
        'guitarist', 'guitar', 'chords', 'instruments', 'bingus', 'sussy', 'Big ass',
        'crewmate', 'Imposter', 'choccy milk', 'thwomp', '🐡', 'brain rot', 'your mom', 'baby',
        'baby farting', 'Admin', 'EMOTE GAME', 'Sega', 'Sega Genesis', 'Newgrounds', 'Gamejolt',
        'Steam', 'Epic Games', 'basket', 'update released', 'Soup Land', 'ROCKET',
        'clash of clans', 'clothes', 'lore', 'fart machine', 'mech', 'Angry Birds',
        'Bad Piggies', 'vlog', 'dataValues', 'machine', 'Thanos', 'porn', 'New emote', 'bought',
        'Sun', 'Moon', 'Friday Night Funkin', 'Mod', 'Minecraft', 'Terraria', 'Roblox',
        'Shaders', '2012', '2016', 'peter', 'GTA 6', 'GTA', 'bananas', 'shanky', 'PEED',
        'Hollow Knight', 'Burrito Bison', 'Taco', 'taxes', 'budget', 'dollars', 'british',
        'fluffy', 'brocolli', 'brain', 'SHIT', 'HELL', 'naked', 'babis', 'kingdom', 'HAHAHA',
        'arabic', 'Rocket League', 'Fortnite', 'mrflimflam', 'Flamingo', 'rap', 'bitch',
        'Poop', 'MARIO', 'crAck', 'Harambe', 'hellish', 'crimes', 'cordy', 'Halal', 'HARAM',
        'Chungus', 'president', 'santa', 'idiot', 'WOW', 'SANS', 'FART', 'Garfield', 'POG',
        'DEINX', 'discord', 'Super', 'Market', 'Mark', 'EXPLOSIVE', 'combat', 'oyster',
        'Epico', 'Grammar', 'SUS', 'fresh', 'matilda', 'sonic', 'corpses', 'Egyptian', 'White',
        'BLACK', 'wacky', 'card', 'credit', 'Tycoon', 'tunas', 'Israelite', 'Saudi',
        'brazilian', 'Luigi', 'shawty'
    ],
    tenorDictionary: [
        'mug', 'Talking Tom', 'Talking Ben', 'Talking Angela', 'IShowSpeed',
        'deepwoken', 'pilgrammed', 'lean', '🤓', 'punapea6', 'dream', 'soup land',
        'phexonia studios', 'idfsgs', 'chips', 'racist', 'superbrohouse', 'deinx', 'bubbley',
        'deinbag', 'another', 'crypyth', 'tordenask', 'lead', 'wovxzers', 'dootings',
        'bartekoklol', 'tuca', 'ballfish', 'kleio', 'crazy', 'cinna', 'btn', 'tree', 'gritzy',
        'ruki', 'henry', 'empsy', 'maks', 'henhen', 'phex', 'icre8', 'bilon', 'fnepp',
        'zekkriel', 'tranzst', 'mance', 'luigistar', 'makos', 'spellbunny', 'scriptedsand',
        'puppet', 'josh', 'spooky', 'catfishhotdog', 'robuk', 'pl0x7', 'lemoardo', 'dundeed',
        'notsam', 'luigiluis', 'trongal', 'mysterymeatwad', 'carlito', 'azureblob',
        'simpremove', 'gobby', 'sayori', 'concern', 'betteruser', 'tix', 'charleh', 'jlol',
        'Vesteria', 'Rogue Lineage', 'tricky', 'zardy', 'madness combat', 'splatoon', 'babis',
        'carrot', 'vinegar', 'mushroom', 'stew', 'shroom', 'peashooter', 'frank', 'carl',
        'oil', 'sunflower', 'chomper', 'piranha', 'fishes', 'fishe', 'fish', 'salami', 'furry',
        'uwu', 'owo', 'flip', 'bottle', 'pork', 'demotion', 'promotion', 'Error', 'spoon',
        'knife', 'african', '😂', 'yup', 'turtle', 'persian', 'Freddy', 'FNAF', 'giraffe',
        'hippopotamus', 'coding', 'ocean', 'egg', 'tool', 'lad', 'lad village', 'GPU', 'CPU',
        'lag', 'imposter', 'Among Us', 'sus', 'homework', 'CHICKEN', 'sosig', 'brogle',
        'Windows 95', 'Windows XP', 'blender', 'Phexonia', 'tf2', 'Bastard', 'obby', 'david',
        'WARIO', 'sandals', 'livestream', 'youtube', 'pickle', 'hot', 'RALEIGH', 'PEED FAMILY',
        'gif', 'nostalgia critic', 'Britain', 'America', 'United Kingdom', 'soup',
        'United States of America', 'WOMEN', 'cat', 'marselo', 'tech support', 'indian',
        'japanese', 'Plants vs Zombies', 'Joe Biden', 'chinese', 'Chinese Republic',
        'french fries', 'german', 'SWITZERLAND', 'denmark', 'Donald Trump', 'portuguese',
        'nigerian', 'russian', 'beach', 'Lego', 'Documentation', 'mcdrive', 'no', 'yes',
        'Rigby', 'Mordecai', 'BENSON', 'park', 'phil', 'Anvil', 'halloween', 'pumpkin',
        'shut up', 'platinum', 'cheats', 'GOLD', 'cake day', 'pizza slice', 'lasagna',
        'quesadilla', 'enchilada', 'Miner\'s Haven', 'berezaa', 'LEGENDARY',
        'Bee Swarm Simulator', 'beta tester', 'creator', 'upvotes', 'downvotes', 'redditor',
        'reddit', 'reddit arguments', 'twitter', 'twitter arguments', 'amongla', 'virus',
        'viruses', 'INSTALL NOW', 'Torrent', 'Github', 'the ESSENCE', 'soup satan', 'soup god',
        'quesley', 'empsy', 'regal', 'deflorestation', 'DONKEY KONG', 'gay chains',
        'Tss crazed', 'ralsei', '👶', '✅', 'PIG', 'cucumber', 'mark\'s pizzeria',
        'dominus pizza', 'pizza hut', 'wendy\'s', 'burger king', 'mcdonalds', 'nugget', 'fat',
        'WTF', 'ROFL', 'XD', 'LMAO', 'LOL', 'Lad', 'griefed', 'Fitmc', '2b2t', 'POPBOB',
        'Jeff', 'Slender', 'Piggy', '🐖', 'Burrito', 'fart channel', '💓', 'Banjo',
        'guitarist', 'guitar', 'instruments', 'bingus', 'sussy', 'crewmate', 'Imposter',
        'choccy milk', 'thwomp', '🐡', 'baby', 'Admin', 'EMOTE GAME', 'Sega', 'Sega Genesis',
        'Newgrounds', 'Gamejolt', 'Steam', 'Epic Games', 'basket', 'update released',
        'Soup Land', 'ROCKET', 'clash of clans', 'lore', 'mech', 'Angry Birds', 'Bad Piggies',
        'machine', 'Thanos', 'Sun', 'Moon', 'Friday Night Funkin', 'Mod', 'Minecraft',
        'Terraria', 'Roblox', 'Shaders', '2012', '2016', 'peter', 'GTA 6', 'GTA', 'bananas',
        'Hollow Knight', 'Burrito Bison', 'Taco', 'taxes', 'budget', 'dollars', 'british',
        'brocolli', 'HELL', 'babis', 'kingdom', 'HAHAHA', 'arabic', 'Rocket League',
        'Fortnite', 'mrflimflam', 'Flamingo', 'rap', 'MARIO', 'crimes', 'cordy', 'Halal',
        'HARAM', 'Chungus', 'president', 'santa', 'WOW', 'FART', 'Garfield', 'POG', 'DEINX',
        'discord', 'Market', 'Mark', 'EXPLOSIVE', 'combat', 'oyster', 'Epico', 'Grammar',
        'SUS', 'fresh', 'matilda', 'sonic', 'Egyptian', 'White', 'BLACK', 'Tycoon', 'tunas',
        'brazilian', 'Luigi'
    ],
    arabConnectors: [
        'basically', 'literally', 'unexpected', 'expected', 'lost',
        'lost his shit', 'grinds', 'since', 'I\'m', 'he\'s', 'she\'s', 'le', 'now', 'says',
        'shitted', 'promoted', 'demoted', 'buttered', 'lagging', 'praying', 'died',
        'streaming', 'skydiving', 'trolled', 'goes viral', 'fight', 'gets fired', 'like',
        'love', 'driving', 'could', 'can', 'that', 'this', 'these', 'those', 'who', 'WHEN',
        'so', 'called out', 'on', 'sued', 'cancelled', 'installed', 'removed', 'muting', 'am',
        'are', 'arrested', 'i', 'you', 'he', 'his', 'her', 'she', 'it', 'that', 'the', 'is',
        'was', 'a', 'an', 'watch', 'play', 'gotta', 'get', 'gaming', 'balling', 'yours',
        'mine', 'your', 'you\'re', 'we\'re', 'they\'re', 'our', 'we', 'they', 'them', 'their',
        'wipe', 'born', 'pissing', 'taken off', 'holed', 'off', 'out', 'flood', 'spamming',
        'buy', 'hacking', 'smelling', 'have', 'become', 'be', 'watching', 'Added'
    ],
    psFiles: ['i broke the json'],
    psPasta: ['i broke the json'],
    funnygifs: ['i broke the json'],
    poopPhrases: ['i broke the json'],
    dmPhrases: ['i broke the json'],
    eightball: [
        'I don\'t know.', 'Maybe...', 'I think so.', 'Of course.', 'I don\'t think so.',
        'I can afirm.', 'No, that\'s wrong.', 'Yes, that\'s right.', 'I assume so.', 'Yes.',
        'No.', 'I have no answers.', 'That\'s true.', 'That\'s false.', 'Isn\'t it obvious?'
    ]
}
dataValues.globaldata = {}

module.exports = dataValues