module.exports = function (msg, fixedchoice) {
    let poopy = this

    function phraseword(phrase) {
        const words = phrase.split(' ')
        return words[Math.floor(Math.random() * words.length)].replace(/[.,!?:;"{}[\]()]/g, '')
    }

    const keys = poopy.special.keys

    const year = new Date(Date.now()).getFullYear()
    const sayoriAdjectives = ['HORNY', 'FARTING', 'RACIST', 'STUPID', 'FEMBOY', 'GAY', 'TRANS', 'UNDERAGED', 'RETARD', 'BITCH', 'ASSHOLE', 'MOTHERFUCKER']
    const adjectives = ['is trans', 'the femboy', 'the futa', 'the idiot', 'the stalker', 'the impostor', 'now sus', 'the nutter', 'the shitter', 'the burger', 'is very annoying', 'big', 'fat', 'is thin', 'is small', 'what', 'is funny', 'noob', 'wtf', 'with pp', 'peed his pants', 'is amongla', 'looks at porn lolololol', 'angry'];
    const shipAdjectives = ['likes', 'you like', 'loves', 'you love', 'you are in love with', 'you should marry', 'with', 'hug', 'your game is now poopoo for'];
    const characters = ['daddy dearest', 'gf', 'pico', 'skid and pump', 'monster', 'mommy mearest', 'senpai', 'tankman', 'whitty', 'carol', 'hex', 'ruv', 'sarvente', 'miku', 'tricky', 'zardy', 'matt', 'garcello', 'shaggy', 'annie', 'tbh creature', 'yippee', 'cheeky', 'bob', 'tabi', 'agoti', 'kapi', 'neon', 'nene', 'monika', 'selever', 'tord', 'impostor', 'trollge', 'tree', 'nonsense', 'hypno', 'sonic.exe', 'sonic.exe', 'sonic.exe', 'sonic.exe', 'morbius', 'deinx', 'ralsei', 'kris', 'susie', 'berdly', 'nikocado', 'ness', 'giygas', 'tails doll', 'lord x', 'tbh', 'sans', 'cuphead', 'bendy', 'niko', 'joe biden', 'sprigatito']
    const options = [
        { text: `im in the ${keys._location.func.call(poopy).toLowerCase()}` },
        { text: 'lol https://tenor.com/view/sus-suspect-among-us-gif-18663592' },
        { text: 'https://tenor.com/view/madness-hank-new-grounds-jump-gif-17044581' },
        { text: 'https://tenor.com/view/friday-night-funkin-hey-boyfriend-gif-21180248' },
        { pings: true, text: 'SHUT UP' },
        { pings: true, text: 'sussy' },
        { text: 'lol' },
        { text: 'among us impostor in madness tricky mod' },
        { text: 'ehat', edit: 'what' },
        { text: `${keys._arab.func.call(poopy).toLowerCase()} is ${keys._arab.func.call(poopy).toLowerCase()}` },
        { text: `${keys._arab.func.call(poopy).toLowerCase()} in ${keys._arab.func.call(poopy).toLowerCase()}` },
        { text: `${keys._arab.func.call(poopy).toLowerCase()} ${keys._arab.func.call(poopy).toLowerCase()} is ${keys._arab.func.call(poopy).toLowerCase()} ${keys._arab.func.call(poopy).toLowerCase()}` },
        { text: `not ${keys._arab.func.call(poopy).toLowerCase()}` },
        { text: keys._arab.func.call(poopy).toLowerCase() },
        { text: keys._funnygif.func.call(poopy) },
        { text: `${keys._funnygif.func.call(poopy)} lmap` },
        { text: `${keys._ps.func.call(poopy)} this is ${keys._activemember.func.call(poopy, msg).toLowerCase()}` },
        { text: `${keys._activemember.func.call(poopy, msg).toLowerCase()} is a ${keys._persontype.func.call(poopy)}` },
        { text: `${keys._activemember.func.call(poopy, msg).toLowerCase()} is a ${keys._insult.func.call(poopy)}` },
        { text: `${keys._activemember.func.call(poopy, msg).toLowerCase()} is ${keys._compliment.func.call(poopy)}` },
        { text: `${keys._arab.func.call(poopy).toLowerCase()}.` },
        { text: keys._persontype.func.call(poopy) },
        { text: `${Math.floor(Math.random() * 256)}.${Math.floor(Math.random() * 256)}.${Math.floor(Math.random() * 256)}.${Math.floor(Math.random() * 256)}`, edit: 'e' },
        { text: `i love ${keys._restaurant.func.call(poopy).toLowerCase()}` },
        { text: `the ${keys._arab.func.call(poopy).toLowerCase()} fandom is dying` },
        { text: `THE VS ${keys._arab.func.call(poopy).toUpperCase()} MOD` },
        { text: `WHAT A ${keys._arab.func.call(poopy).toUpperCase()}` },
        { text: keys._message.func.call(poopy, msg).toLowerCase().replace(/[.!,']/g, '') },
        { text: `they added the ${keys._arab.func.call(poopy).toLowerCase()} big ass` },
        { text: `they added the ${keys._arab.func.call(poopy).toLowerCase()}` },
        { text: `THEY ADDED ${keys._arab.func.call(poopy).toUpperCase()}` },
        { text: `the ${keys._arab.func.call(poopy).toLowerCase()}` },
        { text: `not ${keys._arab.func.call(poopy).toLowerCase()} fetish` },
        { text: `im eating ${keys._restaurantfood.func.call(poopy).toLowerCase()}` },
        { text: `finally a ${keys._arab.func.call(poopy).toLowerCase()} game to ${keys._platform.func.call(poopy).toLowerCase()}` },
        { text: `someone draw ${keys._activemember.func.call(poopy, msg).toLowerCase()} as ${characters[Math.floor(Math.random() * characters.length)]}` },
        { text: `ayo its ${keys._activemember.func.call(poopy, msg).toLowerCase()}` },
        { text: `ayo its ${characters[Math.floor(Math.random() * characters.length)]}` },
        { text: `${keys._arab.func.call(poopy).toLowerCase()} was made in ${Math.floor(Math.random() * (year - 1980)) + 1980} xd` },
        { text: `this will be ${keys._arab.func.call(poopy).toLowerCase()} in ${Math.floor(Math.random() * (year - 2000)) + 2000}` },
        { text: `YOU DONT KILL ${`${keys._arab.func.call(poopy).toUpperCase()} `.repeat(2)}KILLS YOU!!!!!!!!!!!!!!!!` },
        { text: `${keys._arab.func.call(poopy).toLowerCase()} is in the ${characters[Math.floor(Math.random() * characters.length)]} week` },
        { text: `${keys._activemember.func.call(poopy, msg).toLowerCase()} = ${characters[Math.floor(Math.random() * characters.length)]}` },
        { text: `no not big ass ${keys._arab.func.call(poopy).toLowerCase()}` },
        { pings: true, text: 'snat' },
        { pings: true, text: `remove ${keys._noun.func.call(poopy)} from me pls` },
        { text: 'STOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPP' },
        { text: 'WOOOOOOOOOOOOOOOOOOOOOOOOOOOOO' },
        { pings: true, text: 'wjat', edit: 'what' },
        { text: phraseword(keys._message.func.call(poopy, msg)).toLowerCase() },
        { text: `whats ${phraseword(keys._message.func.call(poopy, msg)).toLowerCase()}` },
        { text: 'NO' },
        { text: '🤣 🤣 🤣 🤣 🤣 🤣' },
        { text: 'STOP' },
        { pings: true, text: `they hit the ${keys._animal.func.call(poopy)}` },
        { text: 'WHU', edit: 'WHY' },
        { text: 'nopw', edit: 'nope' },
        { text: `${keys._persontype.func.call(poopy)}  I ate your ${keys._segsy.func.call(poopy)}` },
        { text: `u like ${characters[Math.floor(Math.random() * characters.length)]}s ${keys._segsy.func.call(poopy)}` },
        { pings: true, text: 'WHY' },
        { pings: true, text: `you are ${keys._insult.func.call(poopy)}` },
        { pings: true, text: `you are ${keys._compliment.func.call(poopy)}` },
        { text: 'why' },
        { text: 'GOD HELP ME' },
        { text: `yoo ${keys._food.func.call(poopy)}` },
        { text: `im eating ${keys._food.func.call(poopy)}` },
        { text: 'FUCK YOU' },
        { text: 'ayo' },
        { text: String.fromCodePoint(Math.floor(Math.random() * 26) + 97) },
        { text: 'wtf' },
        { text: keys._country.func.call(poopy).toLowerCase() },
        { text: 'wow' },
        { text: `i dont likr ${keys._activemember.func.call(poopy, msg).toLowerCase()}s ${keys._animal.func.call(poopy)}` },
        { text: 'no' },
        { text: 'not again' },
        { text: `IM NOT ${sayoriAdjectives[Math.floor(Math.random() * sayoriAdjectives.length)]}` },
        { text: `im ${sayoriAdjectives[Math.floor(Math.random() * sayoriAdjectives.length)].toLowerCase()}` },
        { text: 'nooooo' },
        { text: 'stol', edit: 'stop' },
        { text: keys._pspasta.func.call(poopy) },
        { text: keys._city.func.call(poopy).toLowerCase() },
        { pings: true, text: 'no' },
        { text: 'gay' },
        { text: 'i dare someone to post porn on my dm\'s' },
        { text: '._.' },
        { pings: true, text: '' },
        { text: `${msg.author.username.toUpperCase()} WHY` },
        { text: 'BRUH' },
        { text: msg.content },
        { text: 'SUS' },
        { text: keys._sentence.func.call(poopy).toLowerCase().replace(/[.,!?":;]/g, '') },
        { text: 'im underaged' },
        { pings: true, text: 'YOU SUSSY' },
        { text: 'AMOGUS' },
        { text: 'is that friday night porn' },
        { pings: true, text: 'flop' },
        { text: 'i like porn 🥲 🥲 🥲 🥲 🥲 🥲' },
        { text: keys._verb.func.call(poopy) },
        { text: keys._noun.func.call(poopy) },
        { text: keys._adj.func.call(poopy) },
        { pings: true, text: `stupid ${msg.author.username.toLowerCase()}` },
        { text: `not ${msg.author.username.toLowerCase()}` },
        { text: `wth ${msg.author.username.toLowerCase()}` },
        { text: `lol ${msg.author.username.toLowerCase()}` },
        { text: `${msg.author.username.toLowerCase()} ${adjectives[Math.floor(Math.random() * adjectives.length)]}` },
        { text: `${msg.author.username.toLowerCase()}: ${keys._arab.func.call(poopy).toLowerCase()}` },
        { text: `no not ${msg.author.username.toLowerCase()} with ${keys._arab.func.call(poopy).toLowerCase()}` },
        { text: 'ahhhhhhhhhh' },
        { text: `${keys._location.func.call(poopy).toLowerCase()} suuucks` },
        { text: 'why am i a bot' },
        { text: `${msg.author.username.toLowerCase()} ${shipAdjectives[Math.floor(Math.random() * shipAdjectives.length)]} ${keys._activemember.func.call(poopy, msg).toLowerCase()}` },
        { text: `is ${keys._activemember.func.call(poopy, msg).toLowerCase()} hot` },
        { text: `im not pinging ${keys._activemember.func.call(poopy, msg).toLowerCase()}` },
        { text: `${keys._activemember.func.call(poopy, msg).toUpperCase()} IS ${sayoriAdjectives[Math.floor(Math.random() * sayoriAdjectives.length)]} NOT ME` },
        { text: `${keys._activemember.func.call(poopy, msg).toLowerCase()} with the ${keys._noun.func.call(poopy)}` },
        { text: `${keys._activemember.func.call(poopy, msg).toLowerCase()} living in ${keys._country.func.call(poopy).toLowerCase()}` },
        { text: `${keys._activemember.func.call(poopy, msg).toLowerCase()}e` },
        { text: `${keys._adj.func.call(poopy)}e ${keys._activemember.func.call(poopy, msg).toLowerCase()}e` },
        { text: `${keys._activemember.func.call(poopy, msg).toUpperCase()} IS THE ${sayoriAdjectives[Math.floor(Math.random() * sayoriAdjectives.length)]} ${sayoriAdjectives[Math.floor(Math.random() * sayoriAdjectives.length)]} ${sayoriAdjectives[Math.floor(Math.random() * sayoriAdjectives.length)]} ${sayoriAdjectives[Math.floor(Math.random() * sayoriAdjectives.length)]}` },
        { text: msg.author.username.toLowerCase() }
    ]

    let choice = fixedchoice && (typeof (Number(fixedchoice)) == 'number' && (((Number(fixedchoice) - 1) >= options.length - 1 && options[options.length - 1]) || ((Number(fixedchoice) - 1) <= 0 && options[0]) || (isNaN(Number(fixedchoice)) && options[Math.floor(Math.random() * options.length)]) || options[Math.floor(Number(fixedchoice))]) || options[Math.floor(Math.random() * options.length)]) || options[Math.floor(Math.random() * options.length)]

    if (Math.random() < 0.02) choice.edit = 'e'

    return choice
}