const fs = require('fs')

module.exports = function () {
    function randomise(e, t, n) {
        function shuffle(array) {
            var e, t, n = array.length;
            if (0 != n)
                for (; --n;) e = Math.floor(Math.random() * (n + 1)), t = array[n], array[n] = array[e], array[e] = t
        }

        if (Array.isArray(e) || (e = e.split("")), shuffle(e), n) {
            for (var r = new Array, o = 0; o < t; o++) r[o] = e[Math.floor(Math.random() * e.length)];
            return r
        }

        return t > 0 && t < e.length ? e.slice(0, t) : e
    }

    function randomiseNumbers(e, t, n, r) {
        e = parseInt(e)
        t = parseInt(t)
        n = parseInt(n)
        var o = t - e + 1
        var a = [];
        if (r) {
            for (var i = 0; i < n; i++) a[i] = e + Math.floor(Math.random() * o);
            return a
        }
        var s = 1;
        for (i = 0; i < o; i++) s = (n - a.length) / (o - i), Math.random() <= s && a.push(i + e);
        return randomise(a, n, r)
    }

    function randAddressLine1and2() {
        var e = null

        var r = ["10th", "53rd", "1st",
            "2nd", "3rd", "4th", "6th",
            "8th", "Acacia", "Academy",
            "Adams", "Addison",
            "Airport", "Albany",
            "Alderwood", "Alton",
            "Amerige", "Amherst",
            "Anderson", "Andover",
            "Ann", "Annadale",
            "Applegate", "Arcadia",
            "Arch", "Argyle",
            "Arlington", "Armstrong",
            "Arnold", "Arrowhead",
            "Ashley", "Aspen",
            "Atlantic", "Augusta",
            "Baker", "Bald Hill",
            "Bank", "Bay",
            "Bay Meadows", "Bayberry",
            "Bayport", "Beach",
            "Beacon", "Bear Hill",
            "Beaver Ridge", "Bedford",
            "Beech", "Beechwood",
            "Bellevue", "Belmont",
            "Berkshire",
            "Big Rock Cove",
            "Birch Hill", "Birchpond",
            "Birchwood", "Bishop",
            "Blackburn", "Blue Spring",
            "Bohemia", "Border",
            "Boston", "Bow Ridge",
            "Bowman", "Bradford",
            "Branch", "Brandywine",
            "Brewery", "Briarwood",
            "Brickell", "Brickyard",
            "Bridge", "Bridgeton",
            "Bridle", "Broad", "Brook",
            "Brookside", "Brown",
            "Buckingham", "Buttonwood",
            "Cactus", "Cambridge",
            "Campfire", "Canal",
            "Canterbury", "Cardinal",
            "Carpenter", "Carriage",
            "Carson", "Catherine",
            "Cedar", "Cedar Swamp",
            "Cedarwood", "Cemetery",
            "Center", "Central",
            "Chapel", "Charles",
            "Cherry", "Cherry Hill",
            "Chestnut", "Church",
            "Circle", "Clark", "Clay",
            "Cleveland", "Clinton",
            "Cobblestone", "Coffee",
            "College", "Colonial",
            "Columbia", "Constitution",
            "Cooper", "Corona",
            "Cottage", "Country",
            "Country Club", "County",
            "Court", "Courtland",
            "Creek", "Creekside",
            "Crescent", "Cross",
            "Cypress", "Deerfield",
            "Del Monte", "Delaware",
            "Depot", "Devon",
            "Devonshire", "Division",
            "Dogwood", "Dunbar",
            "Durham", "Eagle", "East",
            "Edgefield", "Edgemont",
            "Edgewater", "Edgewood",
            "El Dorado", "Elizabeth",
            "Elm", "Elmwood", "Essex",
            "Euclid", "Evergreen",
            "Fairfield", "Fairground",
            "Fairview", "Fairway",
            "Fawn", "Fieldstone",
            "Fifth", "Fordham",
            "Forest", "Foster",
            "Foxrun", "Franklin",
            "Fremont", "Front",
            "Fulton", "Gainsway",
            "Galvin", "Garden",
            "Garfield", "Gartner",
            "Gates", "George",
            "Glen Creek", "Glen Eagles",
            "Glen Ridge", "Glendale",
            "Glenholme", "Glenlake",
            "Glenridge", "Glenwood",
            "Golden Star ", "Goldfield",
            "Golf", "Gonzales", "Grand",
            "Grandrose", "Grant",
            "Green", "Green Hill",
            "Green Lake", "Greenrose",
            "Greenview", "Gregory",
            "Greystone", "Griffin",
            "Grove", "Gulf", "Halifax",
            "Hall", "Hamilton",
            "Hanover", "Harrison",
            "Hartford", "Harvard",
            "Harvey", "Hawthorne",
            "Heather", "Helen", "Henry",
            "Henry Smith", "Heritage",
            "Hickory", "High",
            "High Noon", "High Point",
            "High Ridge", "Highland",
            "Hill", "Hill Field",
            "Hillcrest", "Hilldale",
            "Hillside", "Hilltop",
            "Holly", "Homestead",
            "Homewood", "Honey Creek",
            "Howard", "Hudson",
            "Illinois", "Indian Spring",
            "Indian Summer",
            "Inverness", "Iroquois",
            "Ivy", "Jackson", "James",
            "Jefferson", "Jennings",
            "Jockey Hollow", "John",
            "Johnson", "Jones",
            "Joy Ridge", "Kent",
            "Ketch Harbour", "King",
            "Kingston", "Kirkland",
            "La Sierra", "Lafayette",
            "Lafayette ", "Lake",
            "Lake Forest", "Lake View",
            "Lakeshore", "Lakeview",
            "Lakewood", "Lancaster",
            "Lantern", "Laurel",
            "Lawrence", "Leatherwood",
            "Lees Creek",
            "Leeton Ridge", "Lexington",
            "Liberty", "Lilac",
            "Lincoln", "Linda",
            "Linden", "Littleton",
            "Livingston", "Locust",
            "Logan", "Longbranch",
            "Longfellow", "Lookout",
            "Lower River", "Lyme",
            "Madison", "Magnolia",
            "Maiden", "Main", "Mammoth",
            "Manchester", "Manhattan",
            "Manor", "Manor Station",
            "Maple", "Marconi",
            "Market", "Marlborough",
            "Marsh", "Marshall",
            "Marvon", "Mayfair",
            "Mayfield", "Mayflower",
            "Meadow", "Meadowbrook",
            "Mechanic", "Middle River",
            "Miles", "Military", "Mill",
            "Mill Pond", "Miller",
            "Monroe", "Morris",
            "Mountainview", "Mulberry",
            "Myers", "Myrtle", "New",
            "New Saddle", "Newbridge",
            "Newcastle", "Newport",
            "Nichols", "Nicolls",
            "North", "Nut Swamp", "Oak",
            "Oak Meadow", "Oak Valley",
            "Oakland", "Oakwood",
            "Ocean", "Ohio", "Oklahoma",
            "Old York", "Olive",
            "Orange", "Orchard",
            "Overlook", "Oxford",
            "Pacific", "Paris Hill",
            "Park", "Parker", "Pawnee",
            "Peachtree", "Pearl",
            "Peg Shop", "Pendergast",
            "Peninsula", "Penn",
            "Pennington",
            "Pennsylvania", "Pheasant",
            "Philmont", "Pierce",
            "Pilgrim", "Pin Oak",
            "Pine", "Pineknoll",
            "Piper", "Pleasant",
            "Plumb Branch", "Plymouth",
            "Poor House", "Poplar",
            "Prairie", "Primrose",
            "Prince", "Princess",
            "Princeton", "Proctor",
            "Prospect", "Pulaski",
            "Pumpkin Hill",
            "Purple Finch", "Queen",
            "Race", "Railroad",
            "Ramblewood",
            "Randall Mill", "Redwood",
            "Richardson", "Ridge",
            "Ridgeview", "Ridgewood",
            "River", "Riverside",
            "Riverview", "Roberts",
            "Rock Creek", "Rock Maple",
            "Rockaway", "Rockcrest",
            "Rockland", "Rockledge",
            "Rockville", "Rockwell",
            "Rocky River", "Roehampton",
            "Roosevelt", "Rose",
            "Rosewood", "Ryan", "Sage",
            "San Carlos", "San Juan",
            "San Pablo", "Santa Clara",
            "Saxon", "Saxton", "School",
            "Schoolhouse", "Second",
            "Selby", "Shadow Brook",
            "Shady", "Sheffield",
            "Sherman", "Sherwood",
            "Shipley", "Shirley",
            "Shore", "Shub Farm",
            "Sierra", "Silver Spear",
            "Sleepy Hollow", "Smith",
            "Smith Store",
            "Smoky Hollow",
            "Snake Hill", "Somerset",
            "South", "Southampton",
            "Spring", "Spruce",
            "Squaw Creek", "St Louis",
            "St Margarets", "St Paul",
            "State", "Stillwater",
            "Stonybrook", "Strawberry",
            "Studebaker", "Sugar",
            "Sulphur Springs", "Summer",
            "Summerhouse", "Summit",
            "Sunbeam", "Sunnyslope",
            "Sunset", "Surrey",
            "Sussex", "Sutor",
            "Swanson", "Sycamore",
            "Tailwater", "Talbot",
            "Tallwood", "Tanglewood",
            "Tarkiln Hill", "Taylor",
            "Temple", "Thatcher",
            "Theatre", "Third",
            "Thomas", "Thompson",
            "Thorne", "Tower",
            "Trenton", "Trout",
            "Trusel", "Tunnel", "Union",
            "University", "Vale",
            "Valley", "Valley Farms",
            "Valley View", "Van Dyke",
            "Vermont", "Vernon",
            "Victoria", "Vine",
            "Virginia", "Wagon",
            "Wakehurst", "Wall",
            "Walnut", "Walnutwood",
            "Walt Whitman", "Warren",
            "Washington", "Water",
            "Wayne", "Wellington",
            "Wentworth", "West",
            "Westminster", "Westport",
            "White", "Whitemarsh",
            "Wild Horse", "Wild Rose",
            "William", "Williams",
            "Willow", "Wilson",
            "Winchester", "Windfall",
            "Winding Way", "Windsor",
            "Wintergreen", "Wood",
            "Woodland", "Woodside",
            "Woodsman", "Wrangler",
            "York", "Young", "Yukon"
        ]

        var a = r[Math.floor(r.length * Math.random())]

        return (e = Math.floor(500 * Math.random())) < 100 && (a = e < 13 ? "West " + a : e < 25 ? "South " + a : e < 37 ? "East " + a : e < 49 ? "North " + a : e < 59 ? "E. " + a : e < 69 ? "N. " + a : e < 79 ? "S. " + a : e < 89 ? "W. " + a : e < 91 ? "NE. " + a : e < 93 ? "NW. " + a : e < 95 ? "SE. " + a : e < 97 ? "SW. " + a : "Old " + a), a += (e = Math.floor(100 * Math.random())) < 25 ? " St." : e < 41 ? " Street" : e < 56 ? " Ave." : e < 65 ? " Drive" : e < 74 ? " Dr." : e < 82 ? " Lane" : e < 87 ? " Rd." : e < 92 ? " Court" : e < 96 ? " Road" : e < 99 ? " Avenue" : " Circle", a = (e = Math.floor(1e3 * Math.random())) < 5 ? e < 2 ? "B " + a : 3 == e ? "A " + a : "C " + a : " " + a, a = (e = Math.floor(1e4 * Math.random())) < 500 ? 1 + e % 9 + a : e < 3e3 ? 1 + e % 99 + a : e < 7e3 ? 1 + e % 999 + a : 1 + e % 9999 + a, (e = Math.floor(1e3 * Math.random())) < 5 && (a += " <br>", a += e < 2 ? "Apt " : 3 == e ? "Unit " : "Suite ", a += (e = Math.floor(1e4 * Math.random())) < 3e3 ? 1 + e % 9 : e < 6e3 ? 1 + e % 99 : e < 9e3 ? 1 + e % 999 : String.fromCharCode(65 + e % 10)), a
    }

    var o = ''
    var r = JSON.parse(fs.readFileSync('./assets/json/zip-codes.json'))
    var a = randomiseNumbers(0, r.data.length - 1, 1, false)

    for (var n = 0; n < a.length; n++) {
        var l = r.data[a[n]].detail
        var i = r.data[a[n]].name
        o += randAddressLine1and2() + " " + l + " " + i
    }

    return o
}